grafana:
  version: 7.4.5
  rooturl: "{{ vault_grafana_rooturl }}"
  smtp:
    host: send.one.com
    port: 25
    user: "{{ vault_grafana_smtp_username }}"
    password: "{{ vault_grafana_smtp_password }}"

influxdb:
  database_name: homeautomation
  default_readusername: "grafana"
  default_readuserpassword: "{{ vault_influx_defaultreaduser_password }}"
