mosquitto:
  version: "1.6.12"
  users:
  - username: admin
    password: "{{ vault_mosquitto_password_admin }}"
  #- username: openhab
  #  password: "{{ vault_mosquitto_password_openhab }}"
  - username: homeassistant
    password: "{{ vault_mosquitto_password_homeassistant }}"
  - username: nodered
    password: "{{ vault_mosquitto_password_nodered }}"
  - username: rpimonitor
    password: "{{ vault_mosquitto_password_rpimonitor }}"
  - username: iot_device
    password: "{{ vault_mosquitto_password_iot_device }}"
  #- username: shelly
  #  password: "{{ vault_mosquitto_password_shelly }}"
  #- username: tasmota
  #  password: "{{ vault_mosquitto_password_tasmota }}"
  #- username: yicamera
  #  password: "{{ vault_mosquitto_password_yicamera }}"
  
  