mosquitto:
  version: "2.0.11"
  users:
  - username: admin
    password: "{{ vault_mosquitto_password_admin }}"
  - username: homeassistant
    password: "{{ vault_mosquitto_password_homeassistant }}"
  - username: nodered
    password: "{{ vault_mosquitto_password_nodered }}"
  - username: rpimonitor
    password: "{{ vault_mosquitto_password_rpimonitor }}"
  - username: iot_device
    password: "{{ vault_mosquitto_password_iot_device }}"
